function deepnet = train_captcha(Train_images, Train_code)
    rng('default');
    hiddenSize1 = 452;

    autoenc1 = trainAutoencoder(Train_images,hiddenSize1, ...
        'MaxEpochs',400, ...
        'L2WeightRegularization',0.004, ...
        'SparsityRegularization',4, ...
        'SparsityProportion',0.15, ...
        'ScaleData', false);
    feat1 = encode(autoenc1,Train_images);
    
    hiddenSize2 = 128;
    autoenc2 = trainAutoencoder(feat1,hiddenSize2, ...
        'MaxEpochs',100, ...
        'L2WeightRegularization',0.002, ...
        'SparsityRegularization',4, ...
        'SparsityProportion',0.1, ...
        'ScaleData', false);
    feat2 = encode(autoenc2,feat1);
    
    softnet = trainSoftmaxLayer(feat2,Train_code,'MaxEpochs',400);
    deepnet = stack(autoenc1,autoenc2,softnet);
    
    xTrain = zeros(1600,numel(Train_images));
    for i = 1:numel(Train_images)
        xTrain(:,i) = Train_images{i}(:);
    end

    deepnet = train(deepnet,xTrain,Train_code);
    view(deepnet);
end